// <auto-generated />
namespace Erp.Cms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class createTable_slides : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createTable_slides));
        
        string IMigrationMetadata.Id
        {
            get { return "201509031535346_createTable_slides"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
